spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import: optional:configserver:http://localhost:8888/

application:
  swagger:
    title: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    contact:
      name: Telefonica del Peru
      url: https://www.telefonica.com.pe
      email: correo@dominio.com
    license:
      type: copyright
      url: https://www.telefonica.com.pe
